title: "Twitter Joints and Project Goods"
author: "Bradley Momberger"
description: "An infodump about stuff I've been working on in my spare time."
subheading: "Bradley Momberger's project notes, &amp; other software stuff that's interesting."
more: "See full post"
url: "http://airhadoken.github.io"
#baseurl: "/contrast" # comment out if in root directory


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

markdown: kramdown
#markdown: redcarpet

redcarpet:
  extensions: ["tables", "footnotes"]

kramdown:
  input: GFM

comments:
  disqus: airhadoken-postach-io
